### PR TITLE
Resolves #28 Implement execution/constants.go & execution/execution.go

### LINKED ISSUE #28: Implement `execution/constants.go` & `execution/execution.go`

### PR DESCRIPTION
**Pull request by ABD-AZE**
Resolves #28 
1)  The code is not compiling as of now as there are errors which need to be resolved
2) All caller functions which are exposed as the client side functions have been wrapped inside go routines.
3) for H256 type I have used geth's Hash type from the common package (github.com/ethereum/go-ethereum/common.Hash)
4) Function name consistency and argument type consistency is to be ensured in the pakcages state.go ,  rpc.go and proof.go  as functions from these are used in the execution.go file.
5) The functions dealing with Filter have not been implemented as I am not sure whether to define the filter type and all its methods ( that would be very tedious: https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/filter.rs). I have checked geth for something similar to the filter type but nothing found.
6) Another thing which I am unsure of is the receipt root calculation, in helios they have used an external crate (https://docs.rs/triehash/latest/triehash/fn.ordered_trie_root.html) which only takes the vector as an input and generates the root hash. I have written the [function](https://github.com/ABD-AZE/selene/blob/dev/execution/execution.go#L421 ) for calculating the receipt root but i am not sure of its correctness.

### CODE REVIEW

**Comment by gerceboss** [comment]
@ABD-AZE , for the 6th you can write unit test to check the correctness for now. Also which `rpc.go` are you talking about??? I don't see any issue created for the execution module

**Comment by gerceboss** [comment]
@ABD-AZE ,  don't you think the person writing `rpc.go` for execution will have to define the `Filter` type as well?

**Comment by ABD-AZE** [comment]
> ??? I don't see any issue created for 

Rpc.go is not issued yet but it would be in the future.

**Comment by ABD-AZE** [comment]
> @ABD-AZE ,  don't you think the person writing `rpc.go` for execution will have to define the `Filter` type as well?
The Filter type used in Helios has been imported from some external crate. For our use I think we would have to define filter type on our own, so what should I do? (I think a separate issue can be assigned to change the types.go file to include the filter type and it's methods)

**Comment by ABD-AZE** [comment]
The Filter type used in Helios has been imported from some external crate. For our use I think we would have to define filter type on our own, so what should I do? (I think a separate issue can be assigned to change the types.go file to include the filter type and it's methods)> @ABD-AZE , for the 6th you can write unit test to check the correctness for now. Also which `rpc.go` are you talking about??? I don't see any issue created for the execution module
>

**Comment by ABD-AZE** [comment]
The Filter type used in Helios has been imported from some external crate. For our use I think we would have to define filter type on our own, so what should I do? (I think a separate issue can be assigned to change the types.go file to include the filter type and it's methods)

**Comment by gerceboss** [comment]
@ABD-AZE , [FilterQuery](https://github.com/ethereum/go-ethereum/blob/6416813cbee3c548a3fe110bb779cd9f9fa47b04/interfaces.go#L170) is defined in Geth and is used to filer logs. This might work out

**Comment by ABD-AZE** [comment]
Okay I'll check it out

**Comment by star-gazer111** [comment]
@ABD-AZE there are some issues because of which the linter workflow is failing for this PR. Can you please look into it?

**Comment by ABD-AZE** [comment]
> @ABD-AZE there are some issues because of which the linter workflow is failing for this PR. Can you please look into it?

@star-gazer111 linter workflow is now running successfully

**Comment by star-gazer111** [comment]
@ABD-AZE can u please rebase? there are conflicting files.

**Comment by star-gazer111** [comment]
@gerceboss can u please review this one while I review #71

**Comment by gerceboss** [comment]
@ABD-AZE , as sugggested earlier , please split this PR in 2
1. execution.go
2. constants.go

**Comment by star-gazer111** [comment]
> @ABD-AZE , as sugggested earlier , please split this PR in 2
> 
> 1. execution.go
> 2. constants.go

@ABD-AZE in favour of what @gerceboss said, please do the same. For splitting use the technique of "staggered PRs".

- Ceate the branch constants.go and you can add your commits here.
- Then you can create the branch execution.go from this constants.go branch, and here you add your commits for execution.go
When opening the PR just make sure to target the previous branch.

**Pull request merged**
