### PR TITLE
Implemented common/errors.go


### LINKED ISSUE #4: Implement `common/errors.go`

### PR DESCRIPTION
**Pull request by ABD-AZE**
Resolves #4

### CODE REVIEW

**Comment by star-gazer111** [comment]
@ABD-AZE did you build the code & run the linter at your own end before pushing the code?

**Comment by ABD-AZE** [comment]
> @ABD-AZE did you build the code & run the linter at your own end before pushing the code?

No sir, didn't know that

**Comment by ABD-AZE** [comment]
Build process didn't produce any logs. I ran the build process using the -v flag and didn't get any logs.

**Comment by star-gazer111** [comment]
Have you written tests for the functions you implemented?

**Comment by ABD-AZE** [comment]
> Have you written tests for the functions you implemented?
> 
> Edit : Also, the build happened successfully right?

Not written tests cause you said the testing part is to be done after implementing the basic structure. As for the build, it happened successfully without any errors

**Pull request merged**
