### PR TITLE
Refactor rpc

### PR DESCRIPTION
**Pull request by DarkLord017**

### CODE REVIEW

**Comment by star-gazer111** [comment]
@DarkLord017 does this PR has any accompnying PRs as well?

**Comment by DarkLord017** [comment]
yep i will also push consensus and types i also refactored them

**Comment by star-gazer111** [comment]
> yep i will also push consensus and types i also refactored them

can you please do this soon?

**Comment by DarkLord017** [comment]
Ok i will push by today

**Comment by DarkLord017** [comment]
Please refer #66 n #65

**Pull request merged**
