### PR TITLE
Test/test execution execution.go

### PR DESCRIPTION
**Pull request by 18aaddy**
This addresses #95 

I have written tests for all functions in `execution/execution.go` except `GetAccount()` and `GetTransactionReceipt()` as they depend on state and need to have valid proofs in order to work. 
I have made some modifications to execution.go which solved some errors. 

This PR depends on my earlier PR #90 as proof.go had been updated in that. It should be merged after PR #90

### CODE REVIEW

**Comment by 18aaddy** [comment]
Here, the test checks are failing because the `CreateAccessList()` function is not yet working correctly, which I have mentioned in issue #89 

The lint is failing because of a for loop in the test file but the loop is needed as it waits for the blocks to be pushed into state before running tests. Without the loop, the test fails. Also, locally it is only a warning, not an error

**Comment by gerceboss** [comment]
@18aaddy  , make changes according to the one that @x-senpai-x writes

**Comment by 18aaddy** [comment]
You mean the types.AccessList PR? #94

**Comment by 18aaddy** [comment]
@gerceboss This PR contains all tests for http_rpc and execution.go and all tests are passing. This can be merged with no need to merge #88 or #90. 
I tried to split the PRs but either the tests aren't passing or there is a merge conflict. 

Then @ABD-AZE  can work on CreateAccessList function. 

The lint is failing because of a for loop, and I tried to replace that but the tests were failing. It is only a warning while running locally.

**Comment by 18aaddy** [comment]
I am closing this PR. PR #100 can be used instead

**Pull request closed without merging**
