### PR TITLE
Implement/consensus/database.go #23

### PR DESCRIPTION
**Pull request by VeerChaurasia**
Implemented Database.go

### CODE REVIEW

**Comment by star-gazer111** [comment]
@VeerChaurasia is this PR ready for review?

**Comment by VeerChaurasia** [comment]
> @VeerChaurasia is this PR ready for review?

If i had to only implement database then yes

**Comment by star-gazer111** [comment]
> Implemented Database.go

consensus types are already implemented here #25 right?

**Comment by VeerChaurasia** [comment]
> > Implemented Database.go
> 
> 
> 
> consensus types are already implemented here #25 right?

Yes the files are beacon.go and basic.go

**Comment by star-gazer111** [comment]
@VeerChaurasia the linter workflow is failing in this. Did u run the linter at your own end?

**Comment by VeerChaurasia** [comment]
> @VeerChaurasia the linter workflow is failing in this. Did u run the linter at your own end?
there is no problem at my side I think as the database.go doesn't need any field from consensus_core.go(in consensus_core.go every field is private maybe this is hwy the whole linter workflow  is failing)

**Comment by star-gazer111** [comment]
> > @VeerChaurasia the linter workflow is failing in this. Did u run the linter at your own end?
> > there is no problem at my side I think as the database.go doesn't need any field from consensus_core.go(in consensus_core.go every field is private maybe this is hwy the whole linter workflow  is failing)

we are also getting errors in beacon.go & types.go as well. Ig we might need another round of cleanup before execution starts getting merged.

**Review by star-gazer111 — APPROVED** [review]

**Comment by VeerChaurasia** [comment]
Yes some of the structs are still not exportable even some functions ig

**Pull request merged**
