### PR TITLE
Recheck consensus test

### PR DESCRIPTION
**Pull request by DarkLord017**

### CODE REVIEW

**Comment by DarkLord017** [comment]
@star-gazer111 please check

**Comment by DarkLord017** [comment]
check @star-gazer111

**Comment by gerceboss** [comment]
@DarkLord017 , please donot add the test files and changes in other files according to them in one PR, better to keep PR for tests distinct.
Either you can split this PR into 2 and the changes you made to other ones in a different PR

**Comment by star-gazer111** [comment]
> better to keep PR for tests distinct.

Good point. This should be taken care of in every PR. @DarkLord017

**Comment by star-gazer111** [comment]
> Either you can split this PR into 2

No need to do it for now I suppose, I have already reviewed this PR for now

**Review by star-gazer111 — APPROVED** [review]

**Pull request merged**
