### PR TITLE
Implemented execution/evm.go

### PR DESCRIPTION
**Pull request by x-senpai-x**
CallInner function left to implement I can't figure out how to implement it . Also changed address field of common/types.go

### CODE REVIEW

**Comment by x-senpai-x** [comment]
@star-gazer111 Although I have written call_inner function but there are several problems: 
stateDB which is being used in geth vm package has a newEvm function which uses statedDB however I'll need to implement all the methods in that interface for it to work

**Comment by x-senpai-x** [comment]
Also an issue of execution/rpc has not been created till now

**Comment by star-gazer111** [comment]
what is the curren status on this @x-senpai-x ?

**Comment by x-senpai-x** [comment]
I am working with veer to resolve callInner . I am hoping it will be resolved be tommorow> what is the curren status on this @x-senpai-x ?

**Comment by x-senpai-x** [comment]
@star-gazer111 could you please help in callInner function . I am unable to implement this

**Comment by gerceboss** [comment]
@x-senpai-x ,,state the difficulty you are facing and in implementing what ?

**Comment by x-senpai-x** [comment]
@gerceboss in the call inner function when we use vm.NewEvm it takes as arguments BlockContext TxContext StateDB chainConfig and config so the  problem is that StateDB here is different from the proofDB that we have implemented in evm.go. 
However in rust NewEvm func (of Revm) uses the ProofDB implemented in evm.rs

**Comment by x-senpai-x** [comment]
actually what I did was I implemented everything apart from call,callInner and getEnv. But now there is a problem in proofDB that has been created

**Comment by gerceboss** [comment]
@x-senpai-x  Please remove files like `.DS_store` , `go.mod` and `go.sum` and rebase  first.

**Pull request closed without merging**
