### PR TITLE
Implement consenus test go

### PR DESCRIPTION
**Pull request by DarkLord017**

### CODE REVIEW

**Comment by DarkLord017** [comment]
1. Consensus test case passed 
2. Made consensus core work by adding json tags 
3. Made serde_utils to handle deserialisation of structs that are required 
4. Some structs are left and also it is improper as importing from utils causes import cycle error

**Comment by DarkLord017** [comment]
@star-gazer111

**Comment by star-gazer111** [comment]
> 4\. Some structs are left and also it is improper as importing from utils causes import cycle error

which one exactly?

**Comment by DarkLord017** [comment]
Seeing serde_utils.go I implemented all the structs that were required to complete the test cases 

Since there was an import cycle issue so I for sake of making the tests work I copied the functions into serde_utils.go 

Structs related to deserialisation of beacon block body are just left

**Comment by DarkLord017** [comment]
Check @star-gazer111

**Review by star-gazer111 — APPROVED** [review]

**Pull request merged**
