### PR TITLE
Fix/implement config base and config config #12

### LINKED ISSUE #12: Implement `config/base.go` and `config/config.go`

### PR DESCRIPTION
**Pull request by 18aaddy**
Resolves #12 
- [x] Implemented config/config.go and config/base.go
- [x] Implemented tests for config.go and base.go (Tests successfully passing)
- [x] Also modified some errors in config/networks.go

### CODE REVIEW

**Comment by 18aaddy** [comment]
@gerceboss @star-gazer111  Review pls

**Comment by star-gazer111** [comment]
@18aaddy why is the CI build check failing here? It should've worked fine from this PR & onwards.

**Comment by gerceboss** [comment]
@18aaddy , `go get github.com/avast/retry-go` ,some packages are not present either or they can't be added check locally as well.

**Comment by 18aaddy** [comment]
@gerceboss @star-gazer111 there was some issue with two imports in checkpoints/checkpoints.go
I added the libraries using `go get github.com/avast/retry-go gopkg.in/yaml.v2` which fixes it.
I can push the modified go.mod and go.sum if it's required

**Comment by star-gazer111** [comment]
> @gerceboss @star-gazer111 there was some issue with two imports in checkpoints/checkpoints.go I added the libraries using `go get github.com/avast/retry-go gopkg.in/yaml.v2` which fixes it.
> 
> CI build is still failing because of consensus/database.go as the functions have not been implemented yet.

fine, the build check should run fine once we have [this](https://github.com/BlocSoc-iitr/selene/issues/23) resolved.

**Comment by gerceboss** [comment]
should we merge then or wait for the other PR first @star-gazer111 ?

**Comment by star-gazer111** [comment]
> should we merge then or wait for the other PR first @star-gazer111 ?

We can merge this once someone has reviewed the PR. I haven't done that, can you please do that

**Pull request merged**
