### PR TITLE
Test/test execution http rpc

### PR DESCRIPTION
**Pull request by 18aaddy**
Solves #87 
- [x] Tested `http_rpc_test.go` locally and made modifications according to it in some files.
- [x] Tests working locally (other than CreateAccessList() function, which is not working, I'll raise an issue for that)

Summary of changes:
- Most changes have been made in functions in `http_rpc.go` as the rpc data that is being sent and received is in form of hex strings. So changes had to be made in the way data was sent and also some structs for receiving data
- I have updates the Transaction struct in `common/types.go` as otherwise, the data was not being unmarshaled. Due to this, I had to update few lines in `consensus/consensus.go`. I have tested the consensus part after this change and it works.
- Also I had to change the `execution/rpc.go` file so that the `ExecutionRpc` interface is satisfied by `HttpRpc`

More explanation can be found in comments above the changes 
**Also the lines of code are increased because of go.mod and go.sum**

### CODE REVIEW

**Comment by gerceboss** [comment]
@18aaddy , can you pass the checks first?
```bash
Error: execution/execution.go:34:11: invalid operation: cannot indirect r (variable of type ExecutionRpc)
Error: execution/execution.go:126:16: cannot use proof.Nonce (variable of type hexutil.Uint64) as uint64 value in struct literal
```
Do you think a local command is needed for build and testing? So that you can comfortably check locally if those things do pass?

**Comment by 18aaddy** [comment]
@gerceboss  I'm not sure why the checks are failing as I don't even have execution/execution.go in the files in this PR

**Comment by gerceboss** [comment]
Try rebasing

**Comment by 18aaddy** [comment]
I've rebased but it's the same error

**Comment by 18aaddy** [comment]
To resolve errors, I had to update the execution.go file, which is giving a merge conflict. The error in the execution.go file will be solved in PR #96 where I have modified the execution.go file

**Comment by gerceboss** [comment]
execution.go by @ABD-AZE is the one that we will follow, please first understand that code and then add the modifications if any

**Comment by 18aaddy** [comment]
I understand the code,  there were some errors I found while testing, and thus I made modifications
In my final execution_test PR, all my final changes are there. That one will work once the CreateAccessList() function is modified. Then all tests will pass

**Pull request closed without merging**
