### PR TITLE
Remove utils from config

### PR DESCRIPTION
**Pull request by DarkLord017**

### CODE REVIEW

**Comment by DarkLord017** [comment]
@star-gazer111

**Comment by star-gazer111** [comment]
U didn't add functions of config/utils in this?

> @star-gazer111

**Comment by DarkLord017** [comment]
Vo common wale utils me present the dono

**Comment by star-gazer111** [comment]
> Vo common wale utils me present the dono

U mean common/utils & config/utils same the?

**Comment by DarkLord017** [comment]
No config utils had byte serialise and deserialise only which was present in common utils

**Comment by star-gazer111** [comment]
Config utils has bytes_serialize & deserialize @DarkLord017

**Comment by star-gazer111** [comment]
> No config utils had byte serialise and deserialise only which was present in common utils

But right now utils.go only has 1 function

**Comment by star-gazer111** [comment]
Cool.

**Review by star-gazer111 — APPROVED** [review]

**Pull request merged**
